version: '3'

services:
  toulbar2restcore:
    container_name: soa
    image: toulbar2restcore
    build:
      context: .
      dockerfile: Toulbar2RestCore/Dockerfile
    ports:
     - 8080:80
     - 8081:443
